name: Release
on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  nightly_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download nightly-release repo
        uses: actions/checkout@v4
        with:
          repository: "ZL-Audio/ZLNightlyRelease"
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_NIGHTLY_RELEASE_DEPLOY_KEY }}

      - name: Release
        run: python3 release.py

      - name: Clean nightly-release repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan newBranch
          git add -A
          git commit -m "clean [skip ci]"
          git branch -D main
          git branch -m main
          git push -f origin main
